services:
  varroa_inference:
    build:
      context: .
      dockerfile: .devcontainer/inference/Dockerfile
      network: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - "/dev/video0:/dev/video0"
    ipc: host
    volumes:
      - /media/luca/Home/datasets/prin/raw/dataset_v2_raw_s32_val:/dataset